### ISSUE TITLE
Οδηγίες εγκατάστασης / χρήσης

### ISSUE THREAD

**Issue by GrSoul** [CerebruxCode/Go#1]
Για τους εντελώς αρχάριους, καλό είναι στο "Πώς θα μάθω;" να προστεθεί το εξής:

Για να μπεις στο φάκελο των μαθημάτων που μόλις κατέβασες δίνεις την εντολή:
```
cd go/src/github.com/CerebruxCode/Go
```

Για να μπεις στο εκάστοτε μάθημα (π.χ. στο "00_package_main"):
```
cd 00_package_main
```

Για να ανοίξεις τον κώδικα και να "παίξεις" με τις τιμές του πρώτου μαθήματος:
```
nano package_main.go
```

Για να τρέξεις την εφαρμογή και να δεις τα αποτελέσματά της:
```
go run package_main.go
```

Παρόμοια είναι η διαδικασία και για τα υπόλοιπα μαθήματα. Απλά μπαίνεις στο φάκελό τους, επεξεργάζεσαι το αρχείο με κατάληξη  ".go" και το τρέχεις με την εντολή "go run".

**Comment by cerebrux** [comment]
Θα ανεβάσω διόρθωση και θα ενημερωθείς για την πορεία του issue ! Ευχαριστώ για το feedback
